
package vista;
import modelo.Archivo;
import javax.swing.JOptionPane;


public class frm_principal extends javax.swing.JFrame {
    private Archivo archivo = new Archivo();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_principal.class.getName());

    /**
     * Creates new form frm_principal
     */
    public frm_principal() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_manejo = new javax.swing.JLabel();
        lbl_txt_archi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_txt = new javax.swing.JTextArea();
        bt_procesar = new javax.swing.JButton();
        lbl_longitud = new javax.swing.JLabel();
        lbl_palabras = new javax.swing.JLabel();
        lbl_primeraletra = new javax.swing.JLabel();
        lbl_ultimaletra = new javax.swing.JLabel();
        lbl_centralletra = new javax.swing.JLabel();
        lbl_primerapalabra = new javax.swing.JLabel();
        lbl_palabracentral = new javax.swing.JLabel();
        lbl_ultimapalabra = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        lbl_e = new javax.swing.JLabel();
        lbl_i = new javax.swing.JLabel();
        lbl_o = new javax.swing.JLabel();
        lbl_u = new javax.swing.JLabel();
        lbl_par = new javax.swing.JLabel();
        lbl_impar = new javax.swing.JLabel();
        lbl_manejo1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_traduccion = new javax.swing.JTextArea();
        lbl_r_longitud = new javax.swing.JLabel();
        lbl_r_palabras = new javax.swing.JLabel();
        lbl_r_primeraletra = new javax.swing.JLabel();
        lbl_r_ultimaletra = new javax.swing.JLabel();
        lbl_r_centralletra = new javax.swing.JLabel();
        lbl_r_primerapalabra = new javax.swing.JLabel();
        lbl_r_palabracentral = new javax.swing.JLabel();
        lbl_r_ultimapalabra = new javax.swing.JLabel();
        lbl_r_a = new javax.swing.JLabel();
        lbl_r_e = new javax.swing.JLabel();
        lbl_r_i = new javax.swing.JLabel();
        lbl_r_o = new javax.swing.JLabel();
        lbl_r_u = new javax.swing.JLabel();
        lbl_r_par = new javax.swing.JLabel();
        lbl_r_impar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        guardar_como = new javax.swing.JMenuItem();
        menu_editar = new javax.swing.JMenu();
        copiar = new javax.swing.JMenuItem();
        cortar = new javax.swing.JMenuItem();
        pegar = new javax.swing.JMenuItem();
        buscar = new javax.swing.JMenuItem();
        reemplazar = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programación II");

        lbl_manejo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_manejo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_manejo.setText("MANEJO DE CADENAS");

        lbl_txt_archi.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lbl_txt_archi.setText("Ingrese un texto o abra un archivo");

        area_txt.setColumns(20);
        area_txt.setRows(5);
        jScrollPane1.setViewportView(area_txt);

        bt_procesar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bt_procesar.setText("Procesar");
        bt_procesar.setToolTipText("Procesar");
        bt_procesar.addActionListener(this::bt_procesarActionPerformed);

        lbl_longitud.setText("Longitud de texto........:");

        lbl_palabras.setText("Total de palabras.........:");

        lbl_primeraletra.setText("Primer letra del texto...:");

        lbl_ultimaletra.setText("Última letra del texto...:");

        lbl_centralletra.setText("Letra central del texto..:");

        lbl_primerapalabra.setText("Primera palabra............:");

        lbl_palabracentral.setText("Palabra central..............:");

        lbl_ultimapalabra.setText("Última palabra..............:");

        lbl_a.setText("Repeticiones de \"A\", \"á\" ó \"á\":");

        lbl_e.setText("Repeticiones de \"E\", \"é\" ó \"É\":");

        lbl_i.setText("Repeticiones de \"I\", \"í\" ó \"Í\":");

        lbl_o.setText("Repeticiones de \"O\", \"ó\" ó \"Ó\":");

        lbl_u.setText("Repeticiones de \"U\", \"ú\" ó \"Ú\":");

        lbl_par.setText("Palabras con cantidad de caracteres par:");

        lbl_impar.setText("Palabras con cantidad de caracteres impar:");

        lbl_manejo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_manejo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_manejo1.setText("TRADUCCIÓN A CLAVE MURCIELAGO");

        area_traduccion.setColumns(20);
        area_traduccion.setRows(5);
        jScrollPane2.setViewportView(area_traduccion);

        lbl_r_longitud.setText("-");

        lbl_r_palabras.setText("-");

        lbl_r_primeraletra.setText("-");

        lbl_r_ultimaletra.setText("-");

        lbl_r_centralletra.setText("-");

        lbl_r_primerapalabra.setText("-");

        lbl_r_palabracentral.setText("-");

        lbl_r_ultimapalabra.setText("-");

        lbl_r_a.setText("-");

        lbl_r_e.setText("-");

        lbl_r_i.setText("-");

        lbl_r_o.setText("-");

        lbl_r_u.setText("-");

        lbl_r_par.setText("-");

        lbl_r_impar.setText("-");

        menu_archivo.setText("Archivo");
        menu_archivo.setToolTipText("Archivo");

        abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        abrir.setText("Abrir");
        abrir.addActionListener(this::abrirActionPerformed);
        menu_archivo.add(abrir);

        guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        guardar.setText("Guardar");
        guardar.addActionListener(this::guardarActionPerformed);
        menu_archivo.add(guardar);

        guardar_como.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        guardar_como.setText("Guardar como");
        guardar_como.addActionListener(this::guardar_comoActionPerformed);
        menu_archivo.add(guardar_como);

        jMenuBar1.add(menu_archivo);

        menu_editar.setText("Editar");
        menu_editar.setToolTipText("Editar");

        copiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        copiar.setText("Copiar");
        copiar.addActionListener(this::copiarActionPerformed);
        menu_editar.add(copiar);

        cortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cortar.setText("Cortar");
        cortar.addActionListener(this::cortarActionPerformed);
        menu_editar.add(cortar);

        pegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        pegar.setText("Pegar");
        pegar.addActionListener(this::pegarActionPerformed);
        menu_editar.add(pegar);

        buscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        buscar.setText("Buscar");
        buscar.addActionListener(this::buscarActionPerformed);
        menu_editar.add(buscar);

        reemplazar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        reemplazar.setText("Reemplazar");
        reemplazar.addActionListener(this::reemplazarActionPerformed);
        menu_editar.add(reemplazar);

        jMenuBar1.add(menu_editar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_manejo)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lbl_txt_archi))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(242, 242, 242)
                            .addComponent(bt_procesar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(lbl_manejo1))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_longitud)
                    .addComponent(lbl_palabras)
                    .addComponent(lbl_primeraletra)
                    .addComponent(lbl_ultimaletra)
                    .addComponent(lbl_centralletra)
                    .addComponent(lbl_primerapalabra)
                    .addComponent(lbl_palabracentral)
                    .addComponent(lbl_ultimapalabra))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_r_ultimapalabra)
                        .addGap(307, 307, 307))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_r_palabracentral)
                            .addComponent(lbl_r_primerapalabra)
                            .addComponent(lbl_r_centralletra)
                            .addComponent(lbl_r_ultimaletra)
                            .addComponent(lbl_r_primeraletra)
                            .addComponent(lbl_r_palabras)
                            .addComponent(lbl_r_longitud))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_u)
                            .addComponent(lbl_o)
                            .addComponent(lbl_i)
                            .addComponent(lbl_e)
                            .addComponent(lbl_a)
                            .addComponent(lbl_impar)
                            .addComponent(lbl_par))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_r_a)
                                    .addComponent(lbl_r_e)
                                    .addComponent(lbl_r_i)
                                    .addComponent(lbl_r_o)
                                    .addComponent(lbl_r_u)))
                            .addComponent(lbl_r_par)
                            .addComponent(lbl_r_impar))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_manejo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_txt_archi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_procesar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_a)
                            .addComponent(lbl_r_a))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_e)
                            .addComponent(lbl_r_e))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_i)
                            .addComponent(lbl_r_i))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_o)
                            .addComponent(lbl_r_o))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_u)
                            .addComponent(lbl_r_u))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_par)
                            .addComponent(lbl_r_par))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_impar)
                            .addComponent(lbl_r_impar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_longitud)
                            .addComponent(lbl_r_longitud))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_palabras)
                            .addComponent(lbl_r_palabras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_primeraletra)
                            .addComponent(lbl_r_primeraletra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ultimaletra)
                            .addComponent(lbl_r_ultimaletra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_centralletra)
                            .addComponent(lbl_r_centralletra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_primerapalabra)
                            .addComponent(lbl_r_primerapalabra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_palabracentral)
                            .addComponent(lbl_r_palabracentral))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ultimapalabra)
                            .addComponent(lbl_r_ultimapalabra))))
                .addGap(51, 51, 51)
                .addComponent(lbl_manejo1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
archivo.abrir(area_txt);
    }//GEN-LAST:event_abrirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
     archivo.guardar(area_txt);
    }//GEN-LAST:event_guardarActionPerformed

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarActionPerformed
     
    area_txt.copy();
    }//GEN-LAST:event_copiarActionPerformed

    private void bt_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_procesarActionPerformed
        String texto = area_txt.getText().trim();

    if (texto.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Ingrese un texto primero");
        return;
    }

    
    lbl_r_longitud.setText(String.valueOf(texto.length()));

   
    String[] palabras = texto.split("\\s+");

    lbl_r_palabras.setText(String.valueOf(palabras.length));

    
    lbl_r_primeraletra.setText(
            String.valueOf(texto.charAt(0)));

   
    lbl_r_ultimaletra.setText(
            String.valueOf(texto.charAt(texto.length() - 1)));

    
    int centro = texto.length() / 2;

    lbl_r_centralletra.setText(
            String.valueOf(texto.charAt(centro)));

    
    lbl_r_primerapalabra.setText(
            palabras[0]);

    
    lbl_r_palabracentral.setText(
            palabras[palabras.length / 2]);

    
    lbl_r_ultimapalabra.setText(
            palabras[palabras.length - 1]);

    

    int a = 0;
    int e = 0;
    int i = 0;
    int o = 0;
    int u = 0;

    for (char c : texto.toCharArray()) {

        switch (Character.toLowerCase(c)) {

            case 'a':
            case 'á':
                a++;
                break;

            case 'e':
            case 'é':
                e++;
                break;

            case 'i':
            case 'í':
                i++;
                break;

            case 'o':
            case 'ó':
                o++;
                break;

            case 'u':
            case 'ú':
                u++;
                break;

        }

    }

    lbl_r_a.setText(String.valueOf(a));
    lbl_r_e.setText(String.valueOf(e));
    lbl_r_i.setText(String.valueOf(i));
    lbl_r_o.setText(String.valueOf(o));
    lbl_r_u.setText(String.valueOf(u));

    

    int pares = 0;
    int impares = 0;

    for (String palabra : palabras) {

        if (palabra.length() % 2 == 0) {

            pares++;

        } else {

            impares++;

        }

    }

    lbl_r_par.setText(String.valueOf(pares));
    lbl_r_impar.setText(String.valueOf(impares));
area_traduccion.setText(
        traducirMurcielago(texto));
    }//GEN-LAST:event_bt_procesarActionPerformed

    private void guardar_comoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_comoActionPerformed
       archivo.guardarComo(area_txt);
    }//GEN-LAST:event_guardar_comoActionPerformed

    private void cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortarActionPerformed
       area_txt.cut();
    }//GEN-LAST:event_cortarActionPerformed

    private void pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegarActionPerformed
     area_txt.paste();
    }//GEN-LAST:event_pegarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
      String textoBuscar = JOptionPane.showInputDialog(
            this,
            "Ingrese el texto a buscar");

    if (textoBuscar == null || textoBuscar.isEmpty()) {
        return;
    }

    String contenido = area_txt.getText();

    int posicion = contenido.toLowerCase()
            .indexOf(textoBuscar.toLowerCase());

    if (posicion >= 0) {

        area_txt.requestFocus();

        area_txt.select(
                posicion,
                posicion + textoBuscar.length());

        JOptionPane.showMessageDialog(
                this,
                "Texto encontrado");

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Texto no encontrado");

    }
    }//GEN-LAST:event_buscarActionPerformed

    private void reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reemplazarActionPerformed
         String buscar = JOptionPane.showInputDialog(
            this,
            "Texto a buscar:");

    if (buscar == null || buscar.isEmpty()) {
        return;
    }

    String reemplazo = JOptionPane.showInputDialog(
            this,
            "Nuevo texto:");

    if (reemplazo == null) {
        return;
    }

    String contenido = area_txt.getText();

    contenido = contenido.replace(buscar, reemplazo);

    area_txt.setText(contenido);

    }//GEN-LAST:event_reemplazarActionPerformed

    /**
     * @param args the command line arguments
     */
    private String traducirMurcielago(String texto) {

    texto = texto.replace("M", "0");
    texto = texto.replace("m", "0");

    texto = texto.replace("U", "1");
texto = texto.replace("u", "1");
texto = texto.replace("Ú", "1");
texto = texto.replace("ú", "1");

    texto = texto.replace("R", "2");
    texto = texto.replace("r", "2");

    texto = texto.replace("C", "3");
    texto = texto.replace("c", "3");

    texto = texto.replace("I", "4");
texto = texto.replace("i", "4");
texto = texto.replace("Í", "4");
texto = texto.replace("í", "4");

    texto = texto.replace("E", "5");
texto = texto.replace("e", "5");
texto = texto.replace("É", "5");
texto = texto.replace("é", "5");

    texto = texto.replace("L", "6");
    texto = texto.replace("l", "6");

texto = texto.replace("A", "7");
texto = texto.replace("a", "7");
texto = texto.replace("Á", "7");
texto = texto.replace("á", "7");

    texto = texto.replace("G", "8");
    texto = texto.replace("g", "8");

    texto = texto.replace("O", "9");
texto = texto.replace("o", "9");
texto = texto.replace("Ó", "9");
texto = texto.replace("ó", "9");
    
    

    return texto;
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JTextArea area_traduccion;
    private javax.swing.JTextArea area_txt;
    private javax.swing.JButton bt_procesar;
    private javax.swing.JMenuItem buscar;
    private javax.swing.JMenuItem copiar;
    private javax.swing.JMenuItem cortar;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem guardar_como;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_centralletra;
    private javax.swing.JLabel lbl_e;
    private javax.swing.JLabel lbl_i;
    private javax.swing.JLabel lbl_impar;
    private javax.swing.JLabel lbl_longitud;
    private javax.swing.JLabel lbl_manejo;
    private javax.swing.JLabel lbl_manejo1;
    private javax.swing.JLabel lbl_o;
    private javax.swing.JLabel lbl_palabracentral;
    private javax.swing.JLabel lbl_palabras;
    private javax.swing.JLabel lbl_par;
    private javax.swing.JLabel lbl_primeraletra;
    private javax.swing.JLabel lbl_primerapalabra;
    private javax.swing.JLabel lbl_r_a;
    private javax.swing.JLabel lbl_r_centralletra;
    private javax.swing.JLabel lbl_r_e;
    private javax.swing.JLabel lbl_r_i;
    private javax.swing.JLabel lbl_r_impar;
    private javax.swing.JLabel lbl_r_longitud;
    private javax.swing.JLabel lbl_r_o;
    private javax.swing.JLabel lbl_r_palabracentral;
    private javax.swing.JLabel lbl_r_palabras;
    private javax.swing.JLabel lbl_r_par;
    private javax.swing.JLabel lbl_r_primeraletra;
    private javax.swing.JLabel lbl_r_primerapalabra;
    private javax.swing.JLabel lbl_r_u;
    private javax.swing.JLabel lbl_r_ultimaletra;
    private javax.swing.JLabel lbl_r_ultimapalabra;
    private javax.swing.JLabel lbl_txt_archi;
    private javax.swing.JLabel lbl_u;
    private javax.swing.JLabel lbl_ultimaletra;
    private javax.swing.JLabel lbl_ultimapalabra;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenu menu_editar;
    private javax.swing.JMenuItem pegar;
    private javax.swing.JMenuItem reemplazar;
    // End of variables declaration//GEN-END:variables
}
